pba:
  build: .
  ports:
    - 8080:8080
  links:
    - db
  environment:
    POSTGRES_PASSWORD: postgres
    CATALINA_OPTS: -Xms1024m -Xmx4096m
  mem_limit: 4096m
  command: sh catalina.sh run
db:
  image: postgres
  environment:
    POSTGRES_PASSWORD: postgres
