pba:
  build: .
  ports:
    - 8080:8080
  links:
    - db
  environment:
    POSTGRES_PASSWORD: postgres
  mem_limit: 4096m
  command: sh catalina.sh run
db:
  image: postgres
  environment:
    POSTGRES_PASSWORD: postgres
