pba:
  image: rxacevedo/docker-pentaho-ee
  ports:
    - 8080:8080
  links:
    - db
  environment:
    PGUSER: postgres
    PGHOST: db
    PGPORT: 5432
    PGDATABASE: postgres
  mem_limit: 8092m
  command: sh -c 'sleep 3; sh startup.sh'
db:
  image: postgres
