pba:
  image: REGISTRY_URL/docker-pentaho-ee
  ports:
    - 8080:8080
  links:
    - db:postgres
  environment:
    PGUSER: postgres
    PGHOST: postgres
    PGPORT: 5432
    PGDATABASE: postgres
  mem_limit: 8092m
  command: bash -c 'sleep 5; ./startup.sh'
db:
  image: postgres
