pba:
  image: REGISTRY_URL/docker-pentaho-ee:5.4.0.1-130
  ports:
    - 8080:8080
  links:
    - db:postgres
  environment:
    PGUSER: postgres
    PGHOST: postgres
    PGPORT: 5432
    PGDATABASE: postgres
  mem_limit: 8092m
  command: sh -c 'sleep 3; sh startup.sh'
db:
  image: postgres
